// redux/actionTypes.js

// AUTHENTICATION APIS ACTIONS
export const API = 'API';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_ERROR = 'USER_ERROR';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const TITLE = 'TITLE';
export const REGISTER = 'REGISTER';
export const USERINFO = 'USERINFO';
export const USERSINFO = 'USERSINFO';
export const NIGHTMODE = 'NIGHTMODE';
export const EDITUSERINFO = 'EDITUSERINFO';

// REQUEST APIS ACTIONS
export const GET_REQUESTS = 'GET_REQUESTS';
export const CHANGE_REQUEST_STATUS = 'CHANGE_REQUEST_STATUS';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const GET_REQUEST = 'GET_REQUEST';
export const ADD_REQUEST = 'ADD_REQUEST';
export const REQUEST_ERR = 'REQUEST_ERR';
export const GET_OUTREQUEST = 'GET_OUTREQUEST';
export const GET_OUTREQUESTS = 'GET_OUTREQUESTS';
export const OUTREQUEST_ERR = 'OUTREQUEST_ERR';

// SERVICE APIS ACTIONS
export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICES = 'GET_SERVICES';
export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SERVICE_ERR = 'SERVICE_ERR';

// LOCATION APIS ACTIONS
export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const LOCATION_ERR = 'LOCATION_ERR';

// PROPERTY APIS ACTIONS
export const GET_PROPERTY = 'GET_PROPERTY';
export const GET_PROPERTYS = 'GET_PROPERTYS';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const EDIT_PROPERTY = 'EDIT_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const PROPERTY_ERR = 'PROPERTY_ERR';

// UX ACTIONS
export const BTNLOADING = 'BTNLOADING';
export const LOCATIONOC = 'LOCATIONOC';
export const PROPERTYOC = 'PROPERTYOC';
export const REQUESTOC = 'REQUESTOC';
export const SERVICEOC = 'SERVICEOC';
export const USEROC = 'USEROC';
export const LOCATIONOC2 = 'LOCATIONOC2';
export const PROPERTYOC2 = 'PROPERTYOC2';
export const REQUESTOC2 = 'REQUESTOC2';
export const REQUESTOC3 = 'REQUESTOC3';
export const REQUESTOC4 = 'REQUESTOC4';
export const SERVICEOC2 = 'SERVICEOC2';
export const USEROC2 = 'USEROC2';
export const REQUESTOC22 = 'REQUESTOC22';
export const REQUESTOC33 = 'REQUESTOC33';
export const REQUESTOC44 = 'REQUESTOC44';
